title: Pilot logbook - IY -
description: "My aviation stuff, pilot logbook and aircraft notes."
theme: jekyll-theme-modernist

lang: en
timezone: UTC

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - local.sh
  - README.md
  - package.json
  - package-lock.json
  - eslint.config.js

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
