name: Broken-links Checker

on:
  schedule:
    # - cron: '0 13 * * 5'
    - cron: '*/5 * * * *'

permissions:
  contents: read
  
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Run Link Checker
        uses: merlos/broken-links@0.2.2
        with:
          url: 'https://aero.algorismi.nl/'
          only-errors: 'true'
